# Generated by Django 3.1.4 on 2021-01-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='vacio', max_length=100, null=True)),
                ('slug', models.CharField(default='vacio', max_length=100, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': True,
            },
        ),
    ]
